[project]
name = "harmony"
version = "0.1.0"
description = "an instant messaging and voice chat application"
readme = "README.md"
requires-python = ">=3.14, <3.15"
dependencies = [
    "fastapi>=0.134.0",
]
